import Head from 'next/head';

// Components
import SectionFirst from '@/components/pages/index/sectionFirst';
import SectionQuestions from '@/components/pages/index/sectionQuestions';
import SectionOrder from '@/components/pages/index/sectionOrder';
import SectionPrice from '@/components/pages/index/sectionPrice';

export default function Home() {

  return (
    <>
      <Head>
        <title>Denis Atwell</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:100,100italic,300,300italic,regular,italic,500,500italic,700,700italic,900,900italic" rel="stylesheet" />
      </Head>

      <SectionFirst />
      <SectionQuestions />
      <SectionOrder />
      <SectionPrice />
      
    </>
  )
}

// export async function getServerSI(context: any) {
//   return {
//     props: {}, // will be passed to the page component as props
//   };
// }